name: ML API CI

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t credit-risk-api ./project

      - name: Run container
        run: |
          docker run -d -p 8000:8000 --name api credit-risk-api
          sleep 10

      - name: Wait for API + Health check
        run: |
          for i in {1..15}; do
            curl -f http://localhost:8000/ && exit 0
            echo "waiting..."
            sleep 2
          done

          echo "FAILED - container logs:"
          docker logs api
          exit 1

      - name: Show container logs
        if: always()
        run: docker logs api

      - name: Stop container
        run: docker stop api